export enum ActionType {
  FETCH_PROFILES_START = 'FETCH_PROFILES_START',
  FETCH_PROFILES_SUCCESS = 'FETCH_PROFILES_SUCCESS',
  FETCH_PROFILES_FAILURE = 'FETCH_PROFILES_FAILURE',

  PROFILES_SEARCHING = 'PROFILES_SEARCHING',

  ADD_CHOSEN_PROFILE = 'ADD_CHOSEN_PROFILE',
  DELETE_CHOSEN_PROFILE = 'DELETE_CHOSEN_PROFILE',
  REPLACE_CHOSEN_PROFILE = 'REPLACE_CHOSEN_PROFILE',
}
